### Generated Features for Unknown dataset

### Feature extraction for elements

In [ ]:
import pandas as pd
df = pd.read_excel("Master file.xlsx")
df

,Names,Lattice_constant,Band_gap,TF,Magnetic moment,M1,M2,X,T1,T2
0,Cr-Cr-C-Cl-OH\t,3.155,\t 0.0,\tTrue,3.7021,Cr,Cr,C,Cl,OH
1,Cr-Cr-C-CN-Br\t,3.180,\t 0.0,\tTrue,3.1953,Cr,Cr,C,CN,Br
2,Cr-Cr-C-CN-Cl\t,3.144,\t 0.0,\tTrue,3.2888,Cr,Cr,C,CN,Cl
3,Cr-Cr-C-CN-CN\t,3.112,\t 0.0,\tTrue,3.3409,Cr,Cr,C,CN,CN
4,Cr-Cr-C-CN-F\t,3.220,\t 0.0,\tTrue,5.9863,Cr,Cr,C,CN,F
...,...,...,...,...,...,...,...,...,...,...
23852,Zr-Nb-C-H-OH\t,3.250,\t 0.0,\tTrue,0.0291,Zr,Nb,C,H,OH
23853,Zr-Nb-N-Br-OH\t,3.424,\t 0.0,\tTrue,0.1071,Zr,Nb,N,Br,OH
23854,Zr-Ti-C-NCS-Br\t,3.382,\t 0.0,\tTrue,0.0017,Zr,Ti,C,NCS,Br
23855,Zr-Ti-C-OCl-NCO\t,3.237,\t 0.0,\tTrue,1.5680,Zr,Ti,C,OCl,NCO
23856,Zr-Ti-C-OCl-NCS\t,3.267,\t 0.0,\tTrue,-1.0742,Zr,Ti,C,OCl,NCS

In [ ]:
df1 = df[df.T1==df.T2]
df1

,Names,Lattice_constant,Band_gap,TF,Magnetic moment,M1,M2,X,T1,T2
3,Cr-Cr-C-CN-CN\t,3.112,\t 0.0,\tTrue,3.3409,Cr,Cr,C,CN,CN
17,Cr-Cr-C-F-F\t,3.263,\t 0.0,\tTrue,6.0000,Cr,Cr,C,F,F
21,Cr-Cr-C-H-H\t,3.012,\t 0.0,\tTrue,3.2421,Cr,Cr,C,H,H
28,Cr-Cr-C-NCO-NCO\t,3.140,\t 0.0,\tTrue,3.5363,Cr,Cr,C,NCO,NCO
39,Cr-Cr-C-NCS-NCS\t,3.188,\t 0.0,\tTrue,3.1676,Cr,Cr,C,NCS,NCS
...,...,...,...,...,...,...,...,...,...,...
23824,Zr-Zr-N-OCN-OCN\t,3.391,\t 0.0,\tTrue,-0.0000,Zr,Zr,N,OCN,OCN
23828,Zr-Zr-N-OH-OH\t,3.305,\t 0.0,\tTrue,0.0317,Zr,Zr,N,OH,OH
23829,Zr-Zr-N-O-O\t,3.284,\t 0.0,\tTrue,0.0000,Zr,Zr,N,O,O
23839,Zr-Zr-N-PO-PO\t,3.258,\t 0.0,\tTrue,0.0000,Zr,Zr,N,PO,PO
23848,Zr-Zr-N-SCN-SCN\t,3.563,\t 0.0,\tTrue,-0.0000,Zr,Zr,N,SCN,SCN

In [ ]:
df1["T1"].unique()

array(['CN', 'F', 'H', 'NCO', 'NCS', 'NO', 'OCl', 'OCN', 'OH', 'O', 'PO',
       'SCN', 'Br', 'Cl'], dtype=object)

In [ ]:
df2 = df1[(df1.T1 != 'F') & (df1.T1 != 'H') & (df1.T1 != 'NO') & (df1.T1 != 'OCl') & (df1.T1 != 'OH')]
df2.T1.unique()

array(['CN', 'NCO', 'NCS', 'OCN', 'O', 'PO', 'SCN', 'Br', 'Cl'],
      dtype=object)

In [ ]:
df2.to_excel("LiML_Alldata.xlsx",index=False)

In [ ]:
M1 = pd.DataFrame({"formula":df2.M1})
M1['target'] = ''
M1

In [ ]:
M2 = pd.DataFrame({"formula":df2.M2})
M2['target'] = ''
M2

In [ ]:
X = pd.DataFrame({"formula":df2.X})
X['target'] = ''
X

In [ ]:
T1 = pd.DataFrame({"formula":df2.T1})
T1['target'] = ''
T1

In [ ]:
! git clone "https://github.com/anthony-wang/BestPractices.git"

Cloning into 'BestPractices'...
remote: Enumerating objects: 157, done.
remote: Counting objects: 100% (157/157), done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 157 (delta 44), reused 124 (delta 21), pack-reused 0
Receiving objects: 100% (157/157), 9.67 MiB | 19.88 MiB/s, done.
Resolving deltas: 100% (44/44), done.

In [ ]:
from CBFV.cbfv.composition import generate_features

In [ ]:
mkdir element_properties

In [ ]:
cd element_properties/

/content/BestPractices/notebooks/cbfv/element_properties

In [ ]:
cp ../../CBFV/element_properties/oliynyk.csv .

In [ ]:
cd /content/

/content

In [ ]:
ls

 BestPractices/   LiML_Alldata.xlsx  'Master file.xlsx'   sample_data/

In [ ]:
X_train_unscaled, y_train, formulae_train, skipped_train = generate_features(M1, elem_prop='oliynyk', drop_duplicates=False, extend_features=True, sum_feat=True)

In [ ]:
X_train_unscaled

In [ ]:
X_train_unscaled.to_excel('M1_features.xlsx', index=False)

In [ ]:
X_train_unscaled_M2, y_train, formulae_train, skipped_train = generate_features(M2, elem_prop='oliynyk', drop_duplicates=False, extend_features=True, sum_feat=True)

In [ ]:
X_train_unscaled_M2

In [ ]:
X_train_unscaled_M2.to_excel('M2_features.xlsx', index=False)

In [ ]:
X_train_unscaled_X, y_train, formulae_train, skipped_train = generate_features(X, elem_prop='oliynyk', drop_duplicates=False, extend_features=True, sum_feat=True)
X_train_unscaled_X.to_excel('X_features.xlsx', index=False)
X_train_unscaled_X

In [ ]:
X_train_unscaled_T1, y_train, formulae_train, skipped_train = generate_features(T1, elem_prop='oliynyk', drop_duplicates=False, extend_features=True, sum_feat=True)
X_train_unscaled_T1.to_excel('T1_features.xlsx', index=False)
X_train_unscaled_T1

### Feature collection to one file

In [ ]:
import pandas as pd
ad = pd.read_excel("LiML_Alldata.xlsx")
ad

,Names,Lattice_constant,Band_gap,TF,Magnetic moment,M1,M2,X,T1,T2
0,Cr-Cr-C-CN-CN\t,3.112,0.0,\tTrue,3.3409,Cr,Cr,C,CN,CN
1,Cr-Cr-C-NCO-NCO\t,3.140,0.0,\tTrue,3.5363,Cr,Cr,C,NCO,NCO
2,Cr-Cr-C-NCS-NCS\t,3.188,0.0,\tTrue,3.1676,Cr,Cr,C,NCS,NCS
3,Cr-Cr-C-OCN-OCN\t,3.148,0.0,\tTrue,3.8890,Cr,Cr,C,OCN,OCN
4,Cr-Cr-C-O-O\t,2.910,0.0,\tTrue,4.0000,Cr,Cr,C,O,O
...,...,...,...,...,...,...,...,...,...,...
1181,Zr-Zr-N-NCS-NCS\t,3.422,0.0,\tTrue,0.0000,Zr,Zr,N,NCS,NCS
1182,Zr-Zr-N-OCN-OCN\t,3.391,0.0,\tTrue,0.0000,Zr,Zr,N,OCN,OCN
1183,Zr-Zr-N-O-O\t,3.284,0.0,\tTrue,0.0000,Zr,Zr,N,O,O
1184,Zr-Zr-N-PO-PO\t,3.258,0.0,\tTrue,0.0000,Zr,Zr,N,PO,PO
1185,Zr-Zr-N-SCN-SCN\t,3.563,0.0,\tTrue,0.0000,Zr,Zr,N,SCN,SCN

In [ ]:
pd.set_option("display.max_columns", None)

In [ ]:
m1d = pd.read_excel("M1_features.xlsx")
m2d = pd.read_excel("M2_features.xlsx")
xd = pd.read_excel("X_features.xlsx")
t1d = pd.read_excel("T1_features.xlsx")

In [ ]:
list(m1d.columns)

['M1',
 'sum_Atomic_Number',
 'sum_Atomic_Weight',
 'sum_Period',
 'sum_group',
 'sum_families',
 'sum_Metal',
 'sum_Nonmetal',
 'sum_Metalliod',
 'sum_Mendeleev_Number',
 'sum_l_quantum_number',
 'sum_Atomic_Radius',
 'sum_Miracle_Radius_[pm]',
 'sum_Covalent_Radius',
 'sum_Zunger_radii_sum',
 'sum_ionic_radius',
 'sum_crystal_radius',
 'sum_Pauling_Electronegativity',
 'sum_MB_electonegativity',
 'sum_Gordy_electonegativity',
 'sum_Mulliken_EN',
 'sum_Allred-Rockow_electronegativity',
 'sum_metallic_valence',
 'sum_number_of_valence_electrons',
 'sum_gilmor_number_of_valence_electron',
 'sum_valence_s',
 'sum_valence_p',
 'sum_valence_d',
 'sum_valence_f',
 'sum_Number_of_unfilled_s_valence_electrons',
 'sum_Number_of_unfilled_p_valence_electrons',
 'sum_Number_of_unfilled_d_valence_electrons',
 'sum_Number_of_unfilled_f_valence_electrons',
 'sum_outer_shell_electrons',
 'sum_1st_ionization_potential_(kJ/mol)',
 'sum_polarizability(A^3)',
 'sum_Melting_point_(K)',
 'sum_Boiling_Point_(K)',
 'sum_Density_(g/mL)',
 'sum_specific_heat_(J/g_K)_',
 'sum_heat_of_fusion_(kJ/mol)_',
 'sum_heat_of_vaporization_(kJ/mol)_',
 'sum_thermal_conductivity_(W/(m_K))_',
 'sum_heat_atomization(kJ/mol)',
 'sum_Cohesive_energy',
 'avg_Atomic_Number',
 'avg_Atomic_Weight',
 'avg_Period',
 'avg_group',
 'avg_families',
 'avg_Metal',
 'avg_Nonmetal',
 'avg_Metalliod',
 'avg_Mendeleev_Number',
 'avg_l_quantum_number',
 'avg_Atomic_Radius',
 'avg_Miracle_Radius_[pm]',
 'avg_Covalent_Radius',
 'avg_Zunger_radii_sum',
 'avg_ionic_radius',
 'avg_crystal_radius',
 'avg_Pauling_Electronegativity',
 'avg_MB_electonegativity',
 'avg_Gordy_electonegativity',
 'avg_Mulliken_EN',
 'avg_Allred-Rockow_electronegativity',
 'avg_metallic_valence',
 'avg_number_of_valence_electrons',
 'avg_gilmor_number_of_valence_electron',
 'avg_valence_s',
 'avg_valence_p',
 'avg_valence_d',
 'avg_valence_f',
 'avg_Number_of_unfilled_s_valence_electrons',
 'avg_Number_of_unfilled_p_valence_electrons',
 'avg_Number_of_unfilled_d_valence_electrons',
 'avg_Number_of_unfilled_f_valence_electrons',
 'avg_outer_shell_electrons',
 'avg_1st_ionization_potential_(kJ/mol)',
 'avg_polarizability(A^3)',
 'avg_Melting_point_(K)',
 'avg_Boiling_Point_(K)',
 'avg_Density_(g/mL)',
 'avg_specific_heat_(J/g_K)_',
 'avg_heat_of_fusion_(kJ/mol)_',
 'avg_heat_of_vaporization_(kJ/mol)_',
 'avg_thermal_conductivity_(W/(m_K))_',
 'avg_heat_atomization(kJ/mol)',
 'avg_Cohesive_energy',
 'var_Atomic_Number',
 'var_Atomic_Weight',
 'var_Period',
 'var_group',
 'var_families',
 'var_Metal',
 'var_Nonmetal',
 'var_Metalliod',
 'var_Mendeleev_Number',
 'var_l_quantum_number',
 'var_Atomic_Radius',
 'var_Miracle_Radius_[pm]',
 'var_Covalent_Radius',
 'var_Zunger_radii_sum',
 'var_ionic_radius',
 'var_crystal_radius',
 'var_Pauling_Electronegativity',
 'var_MB_electonegativity',
 'var_Gordy_electonegativity',
 'var_Mulliken_EN',
 'var_Allred-Rockow_electronegativity',
 'var_metallic_valence',
 'var_number_of_valence_electrons',
 'var_gilmor_number_of_valence_electron',
 'var_valence_s',
 'var_valence_p',
 'var_valence_d',
 'var_valence_f',
 'var_Number_of_unfilled_s_valence_electrons',
 'var_Number_of_unfilled_p_valence_electrons',
 'var_Number_of_unfilled_d_valence_electrons',
 'var_Number_of_unfilled_f_valence_electrons',
 'var_outer_shell_electrons',
 'var_1st_ionization_potential_(kJ/mol)',
 'var_polarizability(A^3)',
 'var_Melting_point_(K)',
 'var_Boiling_Point_(K)',
 'var_Density_(g/mL)',
 'var_specific_heat_(J/g_K)_',
 'var_heat_of_fusion_(kJ/mol)_',
 'var_heat_of_vaporization_(kJ/mol)_',
 'var_thermal_conductivity_(W/(m_K))_',
 'var_heat_atomization(kJ/mol)',
 'var_Cohesive_energy',
 'range_Atomic_Number',
 'range_Atomic_Weight',
 'range_Period',
 'range_group',
 'range_families',
 'range_Metal',
 'range_Nonmetal',
 'range_Metalliod',
 'range_Mendeleev_Number',
 'range_l_quantum_number',
 'range_Atomic_Radius',
 'range_Miracle_Radius_[pm]',
 'range_Covalent_Radius',
 'range_Zunger_radii_sum',
 'range_ionic_radius',
 'range_crystal_radius',
 'range_Pauling_Electronegativity',
 'range_MB_electonegativity',
 'range_Gordy_electonegativity',
 'range_Mulliken_EN',
 'range_Allred-Rockow_electronegativity',
 'range_metallic_valence',
 'range_number_of_valence_electrons',
 'range_gilmor_number_of_valence_electron',
 'range_valence_s',
 'range_valence_p',
 'range_valence_d',
 'range_valence_f',
 'range_Number_of_unfilled_s_valence_electrons',
 'range_Number_of_unfilled_p_valence_electrons',
 'range_Number_of_unfilled_d_valence_electrons',
 'range_Number_of_unfilled_f_valence_electrons',
 'range_outer_shell_electrons',
 'range_1st_ionization_potential_(kJ/mol)',
 'range_polarizability(A^3)',
 'range_Melting_point_(K)',
 'range_Boiling_Point_(K)',
 'range_Density_(g/mL)',
 'range_specific_heat_(J/g_K)_',
 'range_heat_of_fusion_(kJ/mol)_',
 'range_heat_of_vaporization_(kJ/mol)_',
 'range_thermal_conductivity_(W/(m_K))_',
 'range_heat_atomization(kJ/mol)',
 'range_Cohesive_energy']

In [ ]:
extract_columns_M1 = ['sum_Atomic_Weight','sum_Atomic_Number','sum_Period','sum_group','sum_number_of_valence_electrons','sum_1st_ionization_potential_(kJ/mol)','sum_Atomic_Radius','sum_Melting_point_(K)','sum_Boiling_Point_(K)','sum_Pauling_Electronegativity']
new_column = ['M1W','M1AN','M1P','M1G','M1V','M1IE','M1R','M1MP','M1BP','M1χ']
ad[new_column] = m1d[extract_columns_M1]
ad

In [ ]:
extract_columns_M2 = ['sum_Atomic_Weight','sum_Atomic_Number','sum_Period','sum_group','sum_number_of_valence_electrons','sum_1st_ionization_potential_(kJ/mol)','sum_Atomic_Radius','sum_Melting_point_(K)','sum_Boiling_Point_(K)','sum_Pauling_Electronegativity']
new_column2 = ['M2W','M2AN','M2P','M2G','M2V','M2IE','M2R','M2MP','M2BP','M2χ']
ad[new_column2] = m2d[extract_columns_M2]
ad

In [ ]:
extract_columns_X = ['sum_Atomic_Weight','sum_Atomic_Number','sum_Period','sum_group','sum_number_of_valence_electrons','sum_1st_ionization_potential_(kJ/mol)','sum_Atomic_Radius','sum_Melting_point_(K)','sum_Boiling_Point_(K)','sum_Pauling_Electronegativity']
new_column3 = ['XW','XAN','XP','XG','XV','XIE','XR','XMP','XBP','Xχ']
ad[new_column3] = xd[extract_columns_X]
ad

In [ ]:
extract_columns_T1 = ['sum_Atomic_Weight','sum_Atomic_Number','sum_Period','sum_group','sum_number_of_valence_electrons','sum_1st_ionization_potential_(kJ/mol)','sum_Atomic_Radius','sum_Melting_point_(K)','sum_Boiling_Point_(K)','sum_Pauling_Electronegativity']
new_column4 = ['T1W','T1AN','T1P','T1G','T1V','T1IE','T1R','T1MP','T1BP','T1χ']
ad[new_column4] = t1d[extract_columns_T1]
ad

In [ ]:
ad.to_excel('Alldata_halffeatures.xlsx', index=False)

In [ ]:
import pandas as pd
adhalf = pd.read_excel('/content/Alldata_halffeatures.xlsx')
adhalf

In [ ]:
extract_columns_M1E = ['sum_Cohesive_energy','sum_gilmor_number_of_valence_electron','sum_valence_s','sum_valence_p','sum_valence_d','sum_valence_f','sum_Number_of_unfilled_s_valence_electrons','sum_Number_of_unfilled_p_valence_electrons','sum_Number_of_unfilled_d_valence_electrons','sum_Number_of_unfilled_f_valence_electrons']
new_column5 = ['M1CE','M1GVE','M1VS','M1VP','M1VD','M1VF','M1USV','M1UPV','M1UDV','M1UFV']
adhalf[new_column5] = m1d[extract_columns_M1E]
adhalf

In [ ]:
extract_columns_M2E = ['sum_Cohesive_energy','sum_gilmor_number_of_valence_electron','sum_valence_s','sum_valence_p','sum_valence_d','sum_valence_f','sum_Number_of_unfilled_s_valence_electrons','sum_Number_of_unfilled_p_valence_electrons','sum_Number_of_unfilled_d_valence_electrons','sum_Number_of_unfilled_f_valence_electrons']
new_column6 = ['M2CE','M2GVE','M2VS','M2VP','M2VD','M2VF','M2USV','M2UPV','M2UDV','M2UFV']
adhalf[new_column6] = m2d[extract_columns_M2E]
adhalf

In [ ]:
extract_columns_XE = ['sum_gilmor_number_of_valence_electron','sum_valence_p','sum_Number_of_unfilled_p_valence_electrons']
new_column7 = ['XGVE','XVP','XUPV']
adhalf[new_column7] = t1d[extract_columns_XE]
adhalf

In [ ]:
extract_columns_T1E = ['sum_gilmor_number_of_valence_electron','sum_valence_s','sum_valence_p','sum_Number_of_unfilled_p_valence_electrons','sum_Number_of_unfilled_d_valence_electrons','sum_Number_of_unfilled_f_valence_electrons']
new_column6 = ['T1GVE','T1VS','T1VP','T1UPV','T1UDV','T1UFV']
adhalf[new_column6] = t1d[extract_columns_T1E]
adhalf

In [ ]:
adhalf.to_excel('Alldata_mostfeatures.xlsx', index=False)

### Surface Area Feature calculation

In [ ]:
import math
from math import sqrt
import os

In [ ]:
def surface_area(file_name):
  with open(file_name) as file:
    lines = file.readlines()

  a_lat = list(map(float, lines[2].split()))
  a = sqrt(sum([i ** 2 for i in a_lat]))
  b_lat = list(map(float, lines[3].split()))
  b = sqrt(sum([i ** 2 for i in b_lat]))
  c = sqrt((a_lat[0]-b_lat[0])**2+(a_lat[1]-b_lat[1])**2+(a_lat[2]-b_lat[2])**2)
  cosine_angle = (a**2 + b**2 - c**2) / (2 * a * b)

  # Calculate the angle in radians
  angle_rad = math.acos(cosine_angle)

  # Convert the angle to degrees
  gamma = math.degrees(angle_rad)
  area = a*b*math.sin(gamma)
  return area

In [ ]:
import pandas as pd
directory = "/content/POSCAR/"
data = []
for filename in os.listdir(directory):
    file_path = os.path.join(directory, filename)
    if os.path.isfile(file_path):  # Check if it's a file
        surface_area_value = surface_area(file_path)
        data.append((filename, surface_area_value))

# Create a DataFrame from the data list
sa = pd.DataFrame(data, columns=["Filename", "Surface Area"])

sa.to_excel('SCN_surface_area.xlsx')
sa

                     Filename  Surface Area
0    relax_POSCAR_Cr-Cr-C-O-O      4.917301
1  relax_POSCAR_Cr-Cr-C-CN-CN      5.626174

### Feature for LiO

In [1]:
import pandas as pd
LiO = pd.DataFrame({"formula":["LiO2","Li2O2","Li3O2","Li4O2"]})
LiO['target'] = ''
LiO

  formula target
0    LiO2
1   Li2O2
2   Li3O2
3   Li4O2

In [2]:
! git clone "https://github.com/anthony-wang/BestPractices.git"

Cloning into 'BestPractices'...
remote: Enumerating objects: 157, done.
remote: Counting objects: 100% (157/157), done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 157 (delta 44), reused 124 (delta 21), pack-reused 0
Receiving objects: 100% (157/157), 9.67 MiB | 19.42 MiB/s, done.
Resolving deltas: 100% (44/44), done.

In [3]:
cd BestPractices/notebooks/

/content/BestPractices/notebooks

In [4]:
from CBFV.cbfv.composition import generate_features

In [6]:
X_train_unscaled_LiO, y_train, formulae_train, skipped_train = generate_features(LiO, elem_prop='oliynyk', drop_duplicates=False, extend_features=True, sum_feat=True)

Processing Input Data: 100%|██████████| 4/4 [00:00<00:00, 1429.80it/s]

	Featurizing Compositions...

Assigning Features...: 100%|██████████| 4/4 [00:00<00:00, 4839.12it/s]

	Creating Pandas Objects...

In [8]:
X_train_unscaled_LiO

,sum_Atomic_Number,sum_Atomic_Weight,sum_Period,sum_group,sum_families,sum_Metal,sum_Nonmetal,sum_Metalliod,sum_Mendeleev_Number,sum_l_quantum_number,...,range_polarizability(A^3),range_Melting_point_(K),range_Boiling_Point_(K),range_Density_(g/mL),range_specific_heat_(J/g_K)_,range_heat_of_fusion_(kJ/mol)_,range_heat_of_vaporization_(kJ/mol)_,range_thermal_conductivity_(W/(m_K))_,range_heat_atomization(kJ/mol),range_Cohesive_energy
0,19.0,38.9398,6.0,33.0,15.0,1.0,2.0,0.0,175.0,2.0,...,138.144762,39780.3025,581406.25,0.073325,1.7956,1.928502,5077.282151,1792.39024,1936.0,0.245025
1,22.0,45.8808,8.0,34.0,16.0,2.0,2.0,0.0,176.0,2.0,...,138.144762,39780.3025,581406.25,0.073325,1.7956,1.928502,5077.282151,1792.39024,1936.0,0.245025
2,25.0,52.8218,10.0,35.0,17.0,3.0,2.0,0.0,177.0,2.0,...,138.144762,39780.3025,581406.25,0.073325,1.7956,1.928502,5077.282151,1792.39024,1936.0,0.245025
3,28.0,59.7628,12.0,36.0,18.0,4.0,2.0,0.0,178.0,2.0,...,138.144762,39780.3025,581406.25,0.073325,1.7956,1.928502,5077.282151,1792.39024,1936.0,0.245025

In [9]:
X_train_unscaled_LiO.to_excel("LiOfeatures.xlsx", index = False)