In [114]:
import pandas as pd
KnownA = pd.read_excel("/content/A_energies.xlsx")
UnknownA = pd.read_excel("/content/Alldata_mostfeatures_A.xlsx")

In [ ]:
KnownA.columns

In [ ]:
KnownA['Names'] = KnownA['Name']
KnownA.columns

In [ ]:
UnknownA.columns

In [ ]:
UnknownA

In [ ]:
KnownA

In [ ]:
KnownwithfeatureA = UnknownA[UnknownA['Names'].isin(KnownA['Names'])]
KnownwithfeatureA

In [ ]:
KnownwithfeatureA.reset_index(drop=True, inplace=True)
KnownwithfeatureA

In [ ]:
KnownwithfeatureA['A'] = KnownA['A']
KnownwithfeatureA

In [123]:
KnownwithfeatureA.to_excel('KnownwithfeatureA.xlsx', index = False)

In [124]:
import pandas as pd
KnownB = pd.read_excel("/content/B_energies.xlsx")
UnknownB = pd.read_excel("/content/Alldata_mostfeatures_B.xlsx")

In [ ]:
KnownB.columns

In [ ]:
KnownB['Names'] = KnownB['Name']
KnownB.columns

In [ ]:
UnknownB.columns

In [ ]:
KnownwithfeatureB = UnknownB[UnknownB['Names'].isin(KnownB['Names'])]
KnownwithfeatureB

In [ ]:
KnownwithfeatureB.reset_index(drop=True, inplace=True)
KnownwithfeatureB

In [ ]:
KnownwithfeatureB['B'] = KnownB['B']
KnownwithfeatureB

In [131]:
KnownwithfeatureB.to_excel('KnownwithfeatureB.xlsx', index = False)

In [132]:
import pandas as pd
KnownC = pd.read_excel("/content/C_energies.xlsx")
UnknownC = pd.read_excel("/content/Alldata_mostfeatures_C.xlsx")

In [ ]:
KnownC.columns

In [ ]:
KnownC['Names'] = KnownC['Name']
KnownC.columns

In [ ]:
UnknownC.columns

In [ ]:
KnownwithfeatureC = UnknownC[UnknownC['Names'].isin(KnownC['Names'])]
KnownwithfeatureC

In [ ]:
KnownwithfeatureC.reset_index(drop=True, inplace=True)
KnownwithfeatureC

In [ ]:
KnownwithfeatureC['C'] = KnownC['C']
KnownwithfeatureC

In [141]:
KnownwithfeatureC.to_excel('KnownwithfeatureC.xlsx', index = False)

In [142]:
import pandas as pd
KnownD = pd.read_excel("/content/D_energies.xlsx")
UnknownD = pd.read_excel("/content/Alldata_mostfeatures_D.xlsx")

In [143]:
KnownD.columns

Index(['Name', 'D', 'M1', 'M2', 'X', 'T1', 'T2'], dtype='object')

In [144]:
KnownD['Names'] = KnownD['Name']
KnownD.columns

Index(['Name', 'D', 'M1', 'M2', 'X', 'T1', 'T2', 'Names'], dtype='object')

In [145]:
UnknownD.columns

Index(['Names', 'LC', 'BG', 'MM', 'M1', 'M2', 'X', 'T1', 'T2', 'TA', 'M1W',
       'M1AN', 'M1P', 'M1G', 'M1V', 'M1IE', 'M1R', 'M1MP', 'M1BP', 'M1χ',
       'M2W', 'M2AN', 'M2P', 'M2G', 'M2V', 'M2IE', 'M2R', 'M2MP', 'M2BP',
       'M2χ', 'XW', 'XAN', 'XP', 'XG', 'XV', 'XIE', 'XR', 'XMP', 'XBP', 'Xχ',
       'T1W', 'T1AN', 'T1P', 'T1G', 'T1V', 'T1IE', 'T1R', 'T1MP', 'T1BP',
       'T1χ', 'M1CE', 'M1GVE', 'M1VS', 'M1VP', 'M1VD', 'M1VF', 'M1USV',
       'M1UPV', 'M1UDV', 'M1UFV', 'M2CE', 'M2GVE', 'M2VS', 'M2VP', 'M2VD',
       'M2VF', 'M2USV', 'M2UPV', 'M2UDV', 'M2UFV', 'XGVE', 'XVP', 'XUPV',
       'T1GVE', 'T1VS', 'T1VP', 'T1UPV', 'T1UDV', 'T1UFV', 'T1-M1', 'M1-X',
       'X-M2', 'M2-T2', 'SA', 'SW', 'M1TΔIE', 'M1XΔIE', 'M2XΔIE', 'M2TΔIE',
       'M1TΔχ', 'M1XΔχ', 'M2XΔχ', 'M2TΔχ'],
      dtype='object')

In [146]:
KnownwithfeatureD = UnknownD[UnknownD['Names'].isin(KnownD['Names'])]
KnownwithfeatureD

,Names,LC,BG,MM,M1,M2,X,T1,T2,TA,...,SA,SW,M1TΔIE,M1XΔIE,M2XΔIE,M2TΔIE,M1TΔχ,M1XΔχ,M2XΔχ,M2TΔχ
22,Mo-W-N-Br-Br,3.408,0.0,0.0755,Mo,W,N,Br,Br,Br,...,6.745973,1278.464,456,718,632,370,0.80,0.88,0.68,0.60
30,Nb-Ta-N-Br-Br,3.474,0.0,0.1713,Nb,Ta,N,Br,Br,Br,...,7.009505,1278.464,488,750,641,379,1.36,1.44,1.54,1.46
43,Sc-Ta-C-Br-Br,3.425,0.0,0.0000,Sc,Ta,C,Br,Br,Br,...,6.812837,1278.464,507,453,325,379,1.60,1.19,1.05,1.46
48,Sc-V-N-Br-Br,3.374,0.0,1.1487,Sc,V,N,Br,Br,Br,...,6.612749,1278.464,507,769,751,489,1.60,1.68,1.41,1.33
50,Sc-W-N-Br-Br,3.404,0.0,0.0632,Sc,W,N,Br,Br,Br,...,6.728852,1278.464,507,769,632,370,1.60,1.68,0.68,0.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,V-Mo-C-SCN-SCN,3.453,0.0,-0.1209,V,Mo,C,SCN,SCN,N,...,6.924934,224.112,2837,435,402,2804,6.54,0.92,0.39,6.01
1150,Y-Cr-C-SCN-SCN,3.609,0.0,2.9298,Y,Cr,C,SCN,SCN,N,...,7.564729,224.112,2888,486,433,2835,6.95,1.33,0.89,6.51
1152,Y-Hf-C-SCN-SCN,3.638,0.0,0.0140,Y,Hf,C,SCN,SCN,N,...,7.685362,224.112,2888,486,427,2829,6.95,1.33,1.25,6.87
1177,Zr-Nb-N-SCN-SCN,3.543,0.0,0.1060,Zr,Nb,N,SCN,SCN,N,...,7.291003,224.112,2848,762,750,2836,6.84,1.71,1.44,6.57
1182,Zr-W-C-SCN-SCN,3.543,0.0,0.1110,Zr,W,C,SCN,SCN,N,...,7.291886,224.112,2848,446,316,2718,6.84,1.22,0.19,5.81

In [147]:
KnownwithfeatureD.reset_index(drop=True, inplace=True)
KnownwithfeatureD

,Names,LC,BG,MM,M1,M2,X,T1,T2,TA,...,SA,SW,M1TΔIE,M1XΔIE,M2XΔIE,M2TΔIE,M1TΔχ,M1XΔχ,M2XΔχ,M2TΔχ
0,Mo-W-N-Br-Br,3.408,0.0,0.0755,Mo,W,N,Br,Br,Br,...,6.745973,1278.464,456,718,632,370,0.80,0.88,0.68,0.60
1,Nb-Ta-N-Br-Br,3.474,0.0,0.1713,Nb,Ta,N,Br,Br,Br,...,7.009505,1278.464,488,750,641,379,1.36,1.44,1.54,1.46
2,Sc-Ta-C-Br-Br,3.425,0.0,0.0000,Sc,Ta,C,Br,Br,Br,...,6.812837,1278.464,507,453,325,379,1.60,1.19,1.05,1.46
3,Sc-V-N-Br-Br,3.374,0.0,1.1487,Sc,V,N,Br,Br,Br,...,6.612749,1278.464,507,769,751,489,1.60,1.68,1.41,1.33
4,Sc-W-N-Br-Br,3.404,0.0,0.0632,Sc,W,N,Br,Br,Br,...,6.728852,1278.464,507,769,632,370,1.60,1.68,0.68,0.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,V-Mo-C-SCN-SCN,3.453,0.0,-0.1209,V,Mo,C,SCN,SCN,N,...,6.924934,224.112,2837,435,402,2804,6.54,0.92,0.39,6.01
143,Y-Cr-C-SCN-SCN,3.609,0.0,2.9298,Y,Cr,C,SCN,SCN,N,...,7.564729,224.112,2888,486,433,2835,6.95,1.33,0.89,6.51
144,Y-Hf-C-SCN-SCN,3.638,0.0,0.0140,Y,Hf,C,SCN,SCN,N,...,7.685362,224.112,2888,486,427,2829,6.95,1.33,1.25,6.87
145,Zr-Nb-N-SCN-SCN,3.543,0.0,0.1060,Zr,Nb,N,SCN,SCN,N,...,7.291003,224.112,2848,762,750,2836,6.84,1.71,1.44,6.57
146,Zr-W-C-SCN-SCN,3.543,0.0,0.1110,Zr,W,C,SCN,SCN,N,...,7.291886,224.112,2848,446,316,2718,6.84,1.22,0.19,5.81

In [148]:
KnownwithfeatureD['D'] = KnownD['D']
KnownwithfeatureD

<ipython-input-148-9d7f91747727>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  KnownwithfeatureD['D'] = KnownD['D']

,Names,LC,BG,MM,M1,M2,X,T1,T2,TA,...,SW,M1TΔIE,M1XΔIE,M2XΔIE,M2TΔIE,M1TΔχ,M1XΔχ,M2XΔχ,M2TΔχ,D
0,Mo-W-N-Br-Br,3.408,0.0,0.0755,Mo,W,N,Br,Br,Br,...,1278.464,456,718,632,370,0.80,0.88,0.68,0.60,-2.201746
1,Nb-Ta-N-Br-Br,3.474,0.0,0.1713,Nb,Ta,N,Br,Br,Br,...,1278.464,488,750,641,379,1.36,1.44,1.54,1.46,-0.704845
2,Sc-Ta-C-Br-Br,3.425,0.0,0.0000,Sc,Ta,C,Br,Br,Br,...,1278.464,507,453,325,379,1.60,1.19,1.05,1.46,-0.890646
3,Sc-V-N-Br-Br,3.374,0.0,1.1487,Sc,V,N,Br,Br,Br,...,1278.464,507,769,751,489,1.60,1.68,1.41,1.33,-0.952681
4,Sc-W-N-Br-Br,3.404,0.0,0.0632,Sc,W,N,Br,Br,Br,...,1278.464,507,769,632,370,1.60,1.68,0.68,0.60,-0.926088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,V-Mo-C-SCN-SCN,3.453,0.0,-0.1209,V,Mo,C,SCN,SCN,N,...,224.112,2837,435,402,2804,6.54,0.92,0.39,6.01,-2.522914
143,Y-Cr-C-SCN-SCN,3.609,0.0,2.9298,Y,Cr,C,SCN,SCN,N,...,224.112,2888,486,433,2835,6.95,1.33,0.89,6.51,-2.797928
144,Y-Hf-C-SCN-SCN,3.638,0.0,0.0140,Y,Hf,C,SCN,SCN,N,...,224.112,2888,486,427,2829,6.95,1.33,1.25,6.87,-3.425262
145,Zr-Nb-N-SCN-SCN,3.543,0.0,0.1060,Zr,Nb,N,SCN,SCN,N,...,224.112,2848,762,750,2836,6.84,1.71,1.44,6.57,-2.436373
146,Zr-W-C-SCN-SCN,3.543,0.0,0.1110,Zr,W,C,SCN,SCN,N,...,224.112,2848,446,316,2718,6.84,1.22,0.19,5.81,-2.355497

In [149]:
KnownwithfeatureD.to_excel('KnownwithfeatureD.xlsx', index = False)