In [ ]:
import pandas as pd
df = pd.read_excel("Reaction energies A.xlsx")
df

                             Name         A
0    relax_POSCAR_Ta­Cr­N­NCO­NCO -0.940978
1      relax_POSCAR_Hf­Hf­N­Cl­Cl -0.957353
2    relax_POSCAR_Ta­Mo­N­NCO­NCO -0.977867
3      relax_POSCAR_Nb­Cr­N­Cl­Cl -0.981294
4      relax_POSCAR_Ta­Mo­C­Br­Br -1.005679
..                            ...       ...
141     relax_POSCAR_Y­Ta­N­PO­PO -7.003190
142    relax_POSCAR_Sc­Zr­C­PO­PO -7.743943
143     relax_POSCAR_Mo­W­N­Br­Br -8.606299
144      relax_POSCAR_Hf­Cr­N­O­O -8.860760
145     relax_POSCAR_Nb­W­C­CN­CN -9.112473

[146 rows x 2 columns]

In [ ]:
# Define a function to extract atoms from the name after "relax_POSCAR_"
import re
def extract_atoms(name):
    match = re.search(r'relax_POSCAR_(.*)', name)
    if match:
        atoms_part = match.group(1)
        atoms = re.findall(r'[A-Z][a-z]*', atoms_part)
        return atoms
    else:
        return []

In [ ]:
df['Atoms'] = df['Name'].apply(extract_atoms)
df

                             Name         A                          Atoms
0    relax_POSCAR_Ta­Cr­N­NCO­NCO -0.940978  [Ta, Cr, N, N, C, O, N, C, O]
1      relax_POSCAR_Hf­Hf­N­Cl­Cl -0.957353            [Hf, Hf, N, Cl, Cl]
2    relax_POSCAR_Ta­Mo­N­NCO­NCO -0.977867  [Ta, Mo, N, N, C, O, N, C, O]
3      relax_POSCAR_Nb­Cr­N­Cl­Cl -0.981294            [Nb, Cr, N, Cl, Cl]
4      relax_POSCAR_Ta­Mo­C­Br­Br -1.005679            [Ta, Mo, C, Br, Br]
..                            ...       ...                            ...
141     relax_POSCAR_Y­Ta­N­PO­PO -7.003190         [Y, Ta, N, P, O, P, O]
142    relax_POSCAR_Sc­Zr­C­PO­PO -7.743943        [Sc, Zr, C, P, O, P, O]
143     relax_POSCAR_Mo­W­N­Br­Br -8.606299             [Mo, W, N, Br, Br]
144      relax_POSCAR_Hf­Cr­N­O­O -8.860760              [Hf, Cr, N, O, O]
145     relax_POSCAR_Nb­W­C­CN­CN -9.112473         [Nb, W, C, C, N, C, N]

[146 rows x 3 columns]

In [ ]:
M1 = []
M2 = []
X = []
T1 = []
T2 = []
for i in df['Atoms']:
  if len(i) == 5:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(i[3])

  elif len(i) == 7:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:5]))

  elif len(i) == 9:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:6]))

In [ ]:
df["M1"] = M1
df["M2"] = M2
df["X"] = X
df["T1"] = T1
df["T2"] = T1

In [ ]:
df

,Name,A,Atoms,M1,M2,X,T1,T2
0,relax_POSCAR_Ta­Cr­N­NCO­NCO,-0.940978,"[Ta, Cr, N, N, C, O, N, C, O]",Ta,Cr,N,NCO,NCO
1,relax_POSCAR_Hf­Hf­N­Cl­Cl,-0.957353,"[Hf, Hf, N, Cl, Cl]",Hf,Hf,N,Cl,Cl
2,relax_POSCAR_Ta­Mo­N­NCO­NCO,-0.977867,"[Ta, Mo, N, N, C, O, N, C, O]",Ta,Mo,N,NCO,NCO
3,relax_POSCAR_Nb­Cr­N­Cl­Cl,-0.981294,"[Nb, Cr, N, Cl, Cl]",Nb,Cr,N,Cl,Cl
4,relax_POSCAR_Ta­Mo­C­Br­Br,-1.005679,"[Ta, Mo, C, Br, Br]",Ta,Mo,C,Br,Br
...,...,...,...,...,...,...,...,...
141,relax_POSCAR_Y­Ta­N­PO­PO,-7.003190,"[Y, Ta, N, P, O, P, O]",Y,Ta,N,PO,PO
142,relax_POSCAR_Sc­Zr­C­PO­PO,-7.743943,"[Sc, Zr, C, P, O, P, O]",Sc,Zr,C,PO,PO
143,relax_POSCAR_Mo­W­N­Br­Br,-8.606299,"[Mo, W, N, Br, Br]",Mo,W,N,Br,Br
144,relax_POSCAR_Hf­Cr­N­O­O,-8.860760,"[Hf, Cr, N, O, O]",Hf,Cr,N,O,O
145,relax_POSCAR_Nb­W­C­CN­CN,-9.112473,"[Nb, W, C, C, N, C, N]",Nb,W,C,CN,CN

In [ ]:
df = df.drop(["Atoms"], axis=1)
df

                             Name         A  M1  M2  X   T1   T2
0    relax_POSCAR_Ta­Cr­N­NCO­NCO -0.940978  Ta  Cr  N  NCO  NCO
1      relax_POSCAR_Hf­Hf­N­Cl­Cl -0.957353  Hf  Hf  N   Cl   Cl
2    relax_POSCAR_Ta­Mo­N­NCO­NCO -0.977867  Ta  Mo  N  NCO  NCO
3      relax_POSCAR_Nb­Cr­N­Cl­Cl -0.981294  Nb  Cr  N   Cl   Cl
4      relax_POSCAR_Ta­Mo­C­Br­Br -1.005679  Ta  Mo  C   Br   Br
..                            ...       ...  ..  .. ..  ...  ...
141     relax_POSCAR_Y­Ta­N­PO­PO -7.003190   Y  Ta  N   PO   PO
142    relax_POSCAR_Sc­Zr­C­PO­PO -7.743943  Sc  Zr  C   PO   PO
143     relax_POSCAR_Mo­W­N­Br­Br -8.606299  Mo   W  N   Br   Br
144      relax_POSCAR_Hf­Cr­N­O­O -8.860760  Hf  Cr  N    O    O
145     relax_POSCAR_Nb­W­C­CN­CN -9.112473  Nb   W  C   CN   CN

[146 rows x 7 columns]

In [ ]:
df.to_excel("A energies.xlsx",index=False)

In [ ]:
df["T1"].unique()

array(['NCO', 'Cl', 'Br', 'O', 'NCS', 'CN', 'SCN', 'OCN', 'PO'],
      dtype=object)

In [ ]:
import pandas as pd
df = pd.read_excel("Reaction energies B.xlsx")
df

                             Name         B
0    relax_POSCAR_Ti­Nb­N­NCO­NCO -0.155537
1        relax_POSCAR_Hf­Cr­N­O­O -1.385994
2    relax_POSCAR_Sc­Ti­N­NCS­NCS -1.732832
3    relax_POSCAR_Zr­Hf­C­NCS­NCS -1.746979
4     relax_POSCAR_Sc­V­N­NCS­NCS -1.751463
..                            ...       ...
142    relax_POSCAR_Nb­Cr­C­CN­CN -7.486942
143    relax_POSCAR_Ta­Cr­N­CN­CN -7.824532
144     relax_POSCAR_Sc­W­N­Br­Br -7.940370
145  relax_POSCAR_Sc­Cr­N­SCN­SCN -7.975433
146     relax_POSCAR_Y­Zr­C­CN­CN -9.080135

[147 rows x 2 columns]

In [ ]:
df['Atoms'] = df['Name'].apply(extract_atoms)
df

                             Name         B                          Atoms
0    relax_POSCAR_Ti­Nb­N­NCO­NCO -0.155537  [Ti, Nb, N, N, C, O, N, C, O]
1        relax_POSCAR_Hf­Cr­N­O­O -1.385994              [Hf, Cr, N, O, O]
2    relax_POSCAR_Sc­Ti­N­NCS­NCS -1.732832  [Sc, Ti, N, N, C, S, N, C, S]
3    relax_POSCAR_Zr­Hf­C­NCS­NCS -1.746979  [Zr, Hf, C, N, C, S, N, C, S]
4     relax_POSCAR_Sc­V­N­NCS­NCS -1.751463   [Sc, V, N, N, C, S, N, C, S]
..                            ...       ...                            ...
142    relax_POSCAR_Nb­Cr­C­CN­CN -7.486942        [Nb, Cr, C, C, N, C, N]
143    relax_POSCAR_Ta­Cr­N­CN­CN -7.824532        [Ta, Cr, N, C, N, C, N]
144     relax_POSCAR_Sc­W­N­Br­Br -7.940370             [Sc, W, N, Br, Br]
145  relax_POSCAR_Sc­Cr­N­SCN­SCN -7.975433  [Sc, Cr, N, S, C, N, S, C, N]
146     relax_POSCAR_Y­Zr­C­CN­CN -9.080135         [Y, Zr, C, C, N, C, N]

[147 rows x 3 columns]

In [ ]:
M1 = []
M2 = []
X = []
T1 = []
T2 = []
for i in df['Atoms']:
  if len(i) == 5:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(i[3])

  elif len(i) == 7:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:5]))

  elif len(i) == 9:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:6]))

In [ ]:
df["M1"] = M1
df["M2"] = M2
df["X"] = X
df["T1"] = T1
df["T2"] = T1

In [ ]:
df

,Name,B,Atoms,M1,M2,X,T1,T2
0,relax_POSCAR_Ti­Nb­N­NCO­NCO,-0.155537,"[Ti, Nb, N, N, C, O, N, C, O]",Ti,Nb,N,NCO,NCO
1,relax_POSCAR_Hf­Cr­N­O­O,-1.385994,"[Hf, Cr, N, O, O]",Hf,Cr,N,O,O
2,relax_POSCAR_Sc­Ti­N­NCS­NCS,-1.732832,"[Sc, Ti, N, N, C, S, N, C, S]",Sc,Ti,N,NCS,NCS
3,relax_POSCAR_Zr­Hf­C­NCS­NCS,-1.746979,"[Zr, Hf, C, N, C, S, N, C, S]",Zr,Hf,C,NCS,NCS
4,relax_POSCAR_Sc­V­N­NCS­NCS,-1.751463,"[Sc, V, N, N, C, S, N, C, S]",Sc,V,N,NCS,NCS
...,...,...,...,...,...,...,...,...
142,relax_POSCAR_Nb­Cr­C­CN­CN,-7.486942,"[Nb, Cr, C, C, N, C, N]",Nb,Cr,C,CN,CN
143,relax_POSCAR_Ta­Cr­N­CN­CN,-7.824532,"[Ta, Cr, N, C, N, C, N]",Ta,Cr,N,CN,CN
144,relax_POSCAR_Sc­W­N­Br­Br,-7.940370,"[Sc, W, N, Br, Br]",Sc,W,N,Br,Br
145,relax_POSCAR_Sc­Cr­N­SCN­SCN,-7.975433,"[Sc, Cr, N, S, C, N, S, C, N]",Sc,Cr,N,SCN,SCN
146,relax_POSCAR_Y­Zr­C­CN­CN,-9.080135,"[Y, Zr, C, C, N, C, N]",Y,Zr,C,CN,CN

In [ ]:
df = df.drop(["Atoms"], axis=1)
df

                             Name         B  M1  M2  X   T1   T2
0    relax_POSCAR_Ti­Nb­N­NCO­NCO -0.155537  Ti  Nb  N  NCO  NCO
1        relax_POSCAR_Hf­Cr­N­O­O -1.385994  Hf  Cr  N    O    O
2    relax_POSCAR_Sc­Ti­N­NCS­NCS -1.732832  Sc  Ti  N  NCS  NCS
3    relax_POSCAR_Zr­Hf­C­NCS­NCS -1.746979  Zr  Hf  C  NCS  NCS
4     relax_POSCAR_Sc­V­N­NCS­NCS -1.751463  Sc   V  N  NCS  NCS
..                            ...       ...  ..  .. ..  ...  ...
142    relax_POSCAR_Nb­Cr­C­CN­CN -7.486942  Nb  Cr  C   CN   CN
143    relax_POSCAR_Ta­Cr­N­CN­CN -7.824532  Ta  Cr  N   CN   CN
144     relax_POSCAR_Sc­W­N­Br­Br -7.940370  Sc   W  N   Br   Br
145  relax_POSCAR_Sc­Cr­N­SCN­SCN -7.975433  Sc  Cr  N  SCN  SCN
146     relax_POSCAR_Y­Zr­C­CN­CN -9.080135   Y  Zr  C   CN   CN

[147 rows x 7 columns]

In [ ]:
df.to_excel("B energies.xlsx",index=False)

In [ ]:
import pandas as pd
df = pd.read_excel("Reaction energies C.xlsx")
df

                             Name         C
0       relax_POSCAR_Y­Hf­N­CN­CN -9.308586
1      relax_POSCAR_Zr­Hf­C­CN­CN -6.897498
2      relax_POSCAR_Hf­Nb­C­CN­CN -6.365236
3     relax_POSCAR_Zr­W­C­SCN­SCN -6.280662
4      relax_POSCAR_Sc­Ti­N­CN­CN -5.640983
..                            ...       ...
149   relax_POSCAR_Nb­W­C­NCS­NCS -0.767850
150   relax_POSCAR_Ta­W­C­NCS­NCS -0.740597
151  relax_POSCAR_Ta­Mo­N­NCS­NCS -0.718246
152    relax_POSCAR_Hf­Hf­N­Cl­Cl -0.594224
153    relax_POSCAR_Ta­Ta­N­CN­CN -0.414118

[154 rows x 2 columns]

In [ ]:
df['Atoms'] = df['Name'].apply(extract_atoms)
df

                             Name         C                          Atoms
0       relax_POSCAR_Y­Hf­N­CN­CN -9.308586         [Y, Hf, N, C, N, C, N]
1      relax_POSCAR_Zr­Hf­C­CN­CN -6.897498        [Zr, Hf, C, C, N, C, N]
2      relax_POSCAR_Hf­Nb­C­CN­CN -6.365236        [Hf, Nb, C, C, N, C, N]
3     relax_POSCAR_Zr­W­C­SCN­SCN -6.280662   [Zr, W, C, S, C, N, S, C, N]
4      relax_POSCAR_Sc­Ti­N­CN­CN -5.640983        [Sc, Ti, N, C, N, C, N]
..                            ...       ...                            ...
149   relax_POSCAR_Nb­W­C­NCS­NCS -0.767850   [Nb, W, C, N, C, S, N, C, S]
150   relax_POSCAR_Ta­W­C­NCS­NCS -0.740597   [Ta, W, C, N, C, S, N, C, S]
151  relax_POSCAR_Ta­Mo­N­NCS­NCS -0.718246  [Ta, Mo, N, N, C, S, N, C, S]
152    relax_POSCAR_Hf­Hf­N­Cl­Cl -0.594224            [Hf, Hf, N, Cl, Cl]
153    relax_POSCAR_Ta­Ta­N­CN­CN -0.414118        [Ta, Ta, N, C, N, C, N]

[154 rows x 3 columns]

In [ ]:
M1 = []
M2 = []
X = []
T1 = []
T2 = []
for i in df['Atoms']:
  if len(i) == 5:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(i[3])

  elif len(i) == 7:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:5]))

  elif len(i) == 9:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:6]))

In [ ]:
df["M1"] = M1
df["M2"] = M2
df["X"] = X
df["T1"] = T1
df["T2"] = T1

In [ ]:
df

,Name,C,Atoms,M1,M2,X,T1,T2
0,relax_POSCAR_Y­Hf­N­CN­CN,-9.308586,"[Y, Hf, N, C, N, C, N]",Y,Hf,N,CN,CN
1,relax_POSCAR_Zr­Hf­C­CN­CN,-6.897498,"[Zr, Hf, C, C, N, C, N]",Zr,Hf,C,CN,CN
2,relax_POSCAR_Hf­Nb­C­CN­CN,-6.365236,"[Hf, Nb, C, C, N, C, N]",Hf,Nb,C,CN,CN
3,relax_POSCAR_Zr­W­C­SCN­SCN,-6.280662,"[Zr, W, C, S, C, N, S, C, N]",Zr,W,C,SCN,SCN
4,relax_POSCAR_Sc­Ti­N­CN­CN,-5.640983,"[Sc, Ti, N, C, N, C, N]",Sc,Ti,N,CN,CN
...,...,...,...,...,...,...,...,...
149,relax_POSCAR_Nb­W­C­NCS­NCS,-0.767850,"[Nb, W, C, N, C, S, N, C, S]",Nb,W,C,NCS,NCS
150,relax_POSCAR_Ta­W­C­NCS­NCS,-0.740597,"[Ta, W, C, N, C, S, N, C, S]",Ta,W,C,NCS,NCS
151,relax_POSCAR_Ta­Mo­N­NCS­NCS,-0.718246,"[Ta, Mo, N, N, C, S, N, C, S]",Ta,Mo,N,NCS,NCS
152,relax_POSCAR_Hf­Hf­N­Cl­Cl,-0.594224,"[Hf, Hf, N, Cl, Cl]",Hf,Hf,N,Cl,Cl
153,relax_POSCAR_Ta­Ta­N­CN­CN,-0.414118,"[Ta, Ta, N, C, N, C, N]",Ta,Ta,N,CN,CN

In [ ]:
df = df.drop(["Atoms"], axis=1)
df

                             Name         C  M1  M2  X   T1   T2
0       relax_POSCAR_Y­Hf­N­CN­CN -9.308586   Y  Hf  N   CN   CN
1      relax_POSCAR_Zr­Hf­C­CN­CN -6.897498  Zr  Hf  C   CN   CN
2      relax_POSCAR_Hf­Nb­C­CN­CN -6.365236  Hf  Nb  C   CN   CN
3     relax_POSCAR_Zr­W­C­SCN­SCN -6.280662  Zr   W  C  SCN  SCN
4      relax_POSCAR_Sc­Ti­N­CN­CN -5.640983  Sc  Ti  N   CN   CN
..                            ...       ...  ..  .. ..  ...  ...
149   relax_POSCAR_Nb­W­C­NCS­NCS -0.767850  Nb   W  C  NCS  NCS
150   relax_POSCAR_Ta­W­C­NCS­NCS -0.740597  Ta   W  C  NCS  NCS
151  relax_POSCAR_Ta­Mo­N­NCS­NCS -0.718246  Ta  Mo  N  NCS  NCS
152    relax_POSCAR_Hf­Hf­N­Cl­Cl -0.594224  Hf  Hf  N   Cl   Cl
153    relax_POSCAR_Ta­Ta­N­CN­CN -0.414118  Ta  Ta  N   CN   CN

[154 rows x 7 columns]

In [ ]:
df.to_excel("C energies.xlsx",index=False)

In [ ]:
import pandas as pd
df = pd.read_excel("Reaction energies D.xlsx")
df

                             Name         D
0      relax_POSCAR_Sc­Cr­C­CN­CN  1.530586
1    relax_POSCAR_Sc­Ti­N­NCS­NCS -0.035089
2      relax_POSCAR_Ta­Mo­C­Br­Br -0.070624
3        relax_POSCAR_Y­Y­N­Cl­Cl -0.138344
4     relax_POSCAR_Zr­V­C­NCS­NCS -0.388988
..                            ...       ...
142     relax_POSCAR_V­Cr­N­PO­PO -4.135980
143     relax_POSCAR_V­Nb­C­PO­PO -4.231865
144     relax_POSCAR_V­Ta­N­PO­PO -4.240838
145    relax_POSCAR_Ta­Cr­N­CN­CN -6.107655
146    relax_POSCAR_W­W­C­OCN­OCN -9.833334

[147 rows x 2 columns]

In [ ]:
df['Atoms'] = df['Name'].apply(extract_atoms)
df

                             Name         D                          Atoms
0      relax_POSCAR_Sc­Cr­C­CN­CN  1.530586        [Sc, Cr, C, C, N, C, N]
1    relax_POSCAR_Sc­Ti­N­NCS­NCS -0.035089  [Sc, Ti, N, N, C, S, N, C, S]
2      relax_POSCAR_Ta­Mo­C­Br­Br -0.070624            [Ta, Mo, C, Br, Br]
3        relax_POSCAR_Y­Y­N­Cl­Cl -0.138344              [Y, Y, N, Cl, Cl]
4     relax_POSCAR_Zr­V­C­NCS­NCS -0.388988   [Zr, V, C, N, C, S, N, C, S]
..                            ...       ...                            ...
142     relax_POSCAR_V­Cr­N­PO­PO -4.135980         [V, Cr, N, P, O, P, O]
143     relax_POSCAR_V­Nb­C­PO­PO -4.231865         [V, Nb, C, P, O, P, O]
144     relax_POSCAR_V­Ta­N­PO­PO -4.240838         [V, Ta, N, P, O, P, O]
145    relax_POSCAR_Ta­Cr­N­CN­CN -6.107655        [Ta, Cr, N, C, N, C, N]
146    relax_POSCAR_W­W­C­OCN­OCN -9.833334    [W, W, C, O, C, N, O, C, N]

[147 rows x 3 columns]

In [ ]:
M1 = []
M2 = []
X = []
T1 = []
T2 = []
for i in df['Atoms']:
  if len(i) == 5:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(i[3])

  elif len(i) == 7:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:5]))

  elif len(i) == 9:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:6]))

In [ ]:
df["M1"] = M1
df["M2"] = M2
df["X"] = X
df["T1"] = T1
df["T2"] = T1

In [ ]:
df

,Name,D,Atoms,M1,M2,X,T1,T2
0,relax_POSCAR_Sc­Cr­C­CN­CN,1.530586,"[Sc, Cr, C, C, N, C, N]",Sc,Cr,C,CN,CN
1,relax_POSCAR_Sc­Ti­N­NCS­NCS,-0.035089,"[Sc, Ti, N, N, C, S, N, C, S]",Sc,Ti,N,NCS,NCS
2,relax_POSCAR_Ta­Mo­C­Br­Br,-0.070624,"[Ta, Mo, C, Br, Br]",Ta,Mo,C,Br,Br
3,relax_POSCAR_Y­Y­N­Cl­Cl,-0.138344,"[Y, Y, N, Cl, Cl]",Y,Y,N,Cl,Cl
4,relax_POSCAR_Zr­V­C­NCS­NCS,-0.388988,"[Zr, V, C, N, C, S, N, C, S]",Zr,V,C,NCS,NCS
...,...,...,...,...,...,...,...,...
142,relax_POSCAR_V­Cr­N­PO­PO,-4.135980,"[V, Cr, N, P, O, P, O]",V,Cr,N,PO,PO
143,relax_POSCAR_V­Nb­C­PO­PO,-4.231865,"[V, Nb, C, P, O, P, O]",V,Nb,C,PO,PO
144,relax_POSCAR_V­Ta­N­PO­PO,-4.240838,"[V, Ta, N, P, O, P, O]",V,Ta,N,PO,PO
145,relax_POSCAR_Ta­Cr­N­CN­CN,-6.107655,"[Ta, Cr, N, C, N, C, N]",Ta,Cr,N,CN,CN
146,relax_POSCAR_W­W­C­OCN­OCN,-9.833334,"[W, W, C, O, C, N, O, C, N]",W,W,C,OCN,OCN

In [ ]:
df = df.drop(["Atoms"], axis=1)
df

                             Name         D  M1  M2  X   T1   T2
0      relax_POSCAR_Sc­Cr­C­CN­CN  1.530586  Sc  Cr  C   CN   CN
1    relax_POSCAR_Sc­Ti­N­NCS­NCS -0.035089  Sc  Ti  N  NCS  NCS
2      relax_POSCAR_Ta­Mo­C­Br­Br -0.070624  Ta  Mo  C   Br   Br
3        relax_POSCAR_Y­Y­N­Cl­Cl -0.138344   Y   Y  N   Cl   Cl
4     relax_POSCAR_Zr­V­C­NCS­NCS -0.388988  Zr   V  C  NCS  NCS
..                            ...       ...  ..  .. ..  ...  ...
142     relax_POSCAR_V­Cr­N­PO­PO -4.135980   V  Cr  N   PO   PO
143     relax_POSCAR_V­Nb­C­PO­PO -4.231865   V  Nb  C   PO   PO
144     relax_POSCAR_V­Ta­N­PO­PO -4.240838   V  Ta  N   PO   PO
145    relax_POSCAR_Ta­Cr­N­CN­CN -6.107655  Ta  Cr  N   CN   CN
146    relax_POSCAR_W­W­C­OCN­OCN -9.833334   W   W  C  OCN  OCN

[147 rows x 7 columns]

In [ ]:
df.to_excel("D energies.xlsx",index=False)