In [1]:
import pandas as pd
df = pd.read_excel("Reaction energies A.xlsx")
df

                             Name         A
0    relax_POSCAR_Ta­Cr­N­NCO­NCO -0.940978
1      relax_POSCAR_Hf­Hf­N­Cl­Cl -0.957353
2    relax_POSCAR_Ta­Mo­N­NCO­NCO -0.977867
3      relax_POSCAR_Nb­Cr­N­Cl­Cl -0.981294
4      relax_POSCAR_Ta­Mo­C­Br­Br -1.005679
..                            ...       ...
141     relax_POSCAR_Y­Ta­N­PO­PO -7.003190
142    relax_POSCAR_Sc­Zr­C­PO­PO -7.743943
143     relax_POSCAR_Mo­W­N­Br­Br -8.606299
144      relax_POSCAR_Hf­Cr­N­O­O -8.860760
145     relax_POSCAR_Nb­W­C­CN­CN -9.112473

[146 rows x 2 columns]

In [2]:
# Define a function to extract atoms from the name after "relax_POSCAR_"
import re
def extract_atoms(name):
    match = re.search(r'relax_POSCAR_(.*)', name)
    if match:
        atoms_part = match.group(1)
        atoms = re.findall(r'[A-Z][a-z]*', atoms_part)
        return atoms
    else:
        return []

In [3]:
df['Atoms'] = df['Name'].apply(extract_atoms)
df

                             Name         A                          Atoms
0    relax_POSCAR_Ta­Cr­N­NCO­NCO -0.940978  [Ta, Cr, N, N, C, O, N, C, O]
1      relax_POSCAR_Hf­Hf­N­Cl­Cl -0.957353            [Hf, Hf, N, Cl, Cl]
2    relax_POSCAR_Ta­Mo­N­NCO­NCO -0.977867  [Ta, Mo, N, N, C, O, N, C, O]
3      relax_POSCAR_Nb­Cr­N­Cl­Cl -0.981294            [Nb, Cr, N, Cl, Cl]
4      relax_POSCAR_Ta­Mo­C­Br­Br -1.005679            [Ta, Mo, C, Br, Br]
..                            ...       ...                            ...
141     relax_POSCAR_Y­Ta­N­PO­PO -7.003190         [Y, Ta, N, P, O, P, O]
142    relax_POSCAR_Sc­Zr­C­PO­PO -7.743943        [Sc, Zr, C, P, O, P, O]
143     relax_POSCAR_Mo­W­N­Br­Br -8.606299             [Mo, W, N, Br, Br]
144      relax_POSCAR_Hf­Cr­N­O­O -8.860760              [Hf, Cr, N, O, O]
145     relax_POSCAR_Nb­W­C­CN­CN -9.112473         [Nb, W, C, C, N, C, N]

[146 rows x 3 columns]

In [4]:
M1 = []
M2 = []
X = []
T1 = []
T2 = []
for i in df['Atoms']:
  if len(i) == 5:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(i[3])

  elif len(i) == 7:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:5]))

  elif len(i) == 9:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:6]))

In [6]:
df["M1"] = M1
df["M2"] = M2
df["X"] = X
df["T1"] = T1
df["T2"] = T1

In [7]:
df

,Name,A,Atoms,M1,M2,X,T1,T2
0,relax_POSCAR_Ta­Cr­N­NCO­NCO,-0.940978,"[Ta, Cr, N, N, C, O, N, C, O]",Ta,Cr,N,NCO,NCO
1,relax_POSCAR_Hf­Hf­N­Cl­Cl,-0.957353,"[Hf, Hf, N, Cl, Cl]",Hf,Hf,N,Cl,Cl
2,relax_POSCAR_Ta­Mo­N­NCO­NCO,-0.977867,"[Ta, Mo, N, N, C, O, N, C, O]",Ta,Mo,N,NCO,NCO
3,relax_POSCAR_Nb­Cr­N­Cl­Cl,-0.981294,"[Nb, Cr, N, Cl, Cl]",Nb,Cr,N,Cl,Cl
4,relax_POSCAR_Ta­Mo­C­Br­Br,-1.005679,"[Ta, Mo, C, Br, Br]",Ta,Mo,C,Br,Br
...,...,...,...,...,...,...,...,...
141,relax_POSCAR_Y­Ta­N­PO­PO,-7.003190,"[Y, Ta, N, P, O, P, O]",Y,Ta,N,PO,PO
142,relax_POSCAR_Sc­Zr­C­PO­PO,-7.743943,"[Sc, Zr, C, P, O, P, O]",Sc,Zr,C,PO,PO
143,relax_POSCAR_Mo­W­N­Br­Br,-8.606299,"[Mo, W, N, Br, Br]",Mo,W,N,Br,Br
144,relax_POSCAR_Hf­Cr­N­O­O,-8.860760,"[Hf, Cr, N, O, O]",Hf,Cr,N,O,O
145,relax_POSCAR_Nb­W­C­CN­CN,-9.112473,"[Nb, W, C, C, N, C, N]",Nb,W,C,CN,CN

In [9]:
df = df.drop(["Atoms"], axis=1)
df

                             Name         A  M1  M2  X   T1   T2
0    relax_POSCAR_Ta­Cr­N­NCO­NCO -0.940978  Ta  Cr  N  NCO  NCO
1      relax_POSCAR_Hf­Hf­N­Cl­Cl -0.957353  Hf  Hf  N   Cl   Cl
2    relax_POSCAR_Ta­Mo­N­NCO­NCO -0.977867  Ta  Mo  N  NCO  NCO
3      relax_POSCAR_Nb­Cr­N­Cl­Cl -0.981294  Nb  Cr  N   Cl   Cl
4      relax_POSCAR_Ta­Mo­C­Br­Br -1.005679  Ta  Mo  C   Br   Br
..                            ...       ...  ..  .. ..  ...  ...
141     relax_POSCAR_Y­Ta­N­PO­PO -7.003190   Y  Ta  N   PO   PO
142    relax_POSCAR_Sc­Zr­C­PO­PO -7.743943  Sc  Zr  C   PO   PO
143     relax_POSCAR_Mo­W­N­Br­Br -8.606299  Mo   W  N   Br   Br
144      relax_POSCAR_Hf­Cr­N­O­O -8.860760  Hf  Cr  N    O    O
145     relax_POSCAR_Nb­W­C­CN­CN -9.112473  Nb   W  C   CN   CN

[146 rows x 7 columns]

In [10]:
df.to_excel("A energies.xlsx",index=False)

In [12]:
df["T1"].unique()

array(['NCO', 'Cl', 'Br', 'O', 'NCS', 'CN', 'SCN', 'OCN', 'PO'],
      dtype=object)

In [ ]:
import pandas as pd
df = pd.read_excel("Reaction energies B.xlsx")
df

In [ ]:
df['Atoms'] = df['Name'].apply(extract_atoms)
df

In [15]:
M1 = []
M2 = []
X = []
T1 = []
T2 = []
for i in df['Atoms']:
  if len(i) == 5:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(i[3])

  elif len(i) == 7:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:5]))

  elif len(i) == 9:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:6]))

In [16]:
df["M1"] = M1
df["M2"] = M2
df["X"] = X
df["T1"] = T1
df["T2"] = T1

In [ ]:
df = df.drop(["Atoms"], axis=1)
df

In [19]:
df.to_excel("B energies.xlsx",index=False)

In [ ]:
import pandas as pd
df = pd.read_excel("Reaction energies C.xlsx")
df

In [ ]:
df['Atoms'] = df['Name'].apply(extract_atoms)
df

In [22]:
M1 = []
M2 = []
X = []
T1 = []
T2 = []
for i in df['Atoms']:
  if len(i) == 5:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(i[3])

  elif len(i) == 7:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:5]))

  elif len(i) == 9:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:6]))

In [23]:
df["M1"] = M1
df["M2"] = M2
df["X"] = X
df["T1"] = T1
df["T2"] = T1

In [ ]:
df = df.drop(["Atoms"], axis=1)
df

In [26]:
df.to_excel("C energies.xlsx",index=False)

In [ ]:
import pandas as pd
df = pd.read_excel("Reaction energies D.xlsx")
df

In [ ]:
df['Atoms'] = df['Name'].apply(extract_atoms)
df

In [29]:
M1 = []
M2 = []
X = []
T1 = []
T2 = []
for i in df['Atoms']:
  if len(i) == 5:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(i[3])

  elif len(i) == 7:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:5]))

  elif len(i) == 9:
    M1.append(i[0])
    M2.append(i[1])
    X.append(i[2])
    T1.append(''.join(i[3:6]))

In [30]:
df["M1"] = M1
df["M2"] = M2
df["X"] = X
df["T1"] = T1
df["T2"] = T1

In [ ]:
df = df.drop(["Atoms"], axis=1)
df

In [33]:
df.to_excel("D energies.xlsx",index=False)